### ISSUE TITLE
Add entities to manifest

### ISSUE THREAD

**Issue by jweisman** [geocode64/delete-sets#17]
Hi there. I demoed this great app today and noticed that there was no [entities attribute](https://developers.exlibrisgroup.com/cloudapps/docs/manifest/#entities) in the manifest. If you add this to the manifest it will be "recommended" by Alma when viewing the Sets list:
```
"entities": [ "SET" ],
```

**Comment by geocode64** [comment]
Thanks @jweisman, implemented in release v1.1
