### ISSUE TITLE
After deleting sets, sets remain in app list, page refreshes a few times

### ISSUE THREAD

**Issue by patriciawf** [geocode64/delete-sets#3]
I found that once I'd deleted some sets, the page refreshed but the list of sets in the app did not. Then the page refreshed again three of four more times, until it finally stopped (but the app still had the deleted sets listed). When I went back to the app list & back into the Delete Sets list, the sets were gone.

![image](https://user-images.githubusercontent.com/80810015/111728709-6678ad00-88a8-11eb-9e84-1f5cb3443216.png)

**Comment by bobo-githut** [comment]
> I found that once I'd deleted some sets, the page refreshed but the list of sets in the app did not. Then the page refreshed again three of four more times, until it finally stopped (but the app still had the deleted sets listed). When I went back to the app list & back into the Delete Sets list, the sets were gone.
> 
> ![image](https://user-images.githubusercontent.com/80810015/111728709-6678ad00-88a8-11eb-9e84-1f5cb3443216.png)

It may cause by API call delay. In our app, we didn't use parallel process to delete sets. So if delete lots in one go, it may take a while.

**Comment by geocode64** [comment]
@bobo-githut do you wan to have a go at rewriting this so the API calls are async?

**Comment by geocode64** [comment]
all good, i've refacted to use parallel deleting as per @bobo-githut  suggestion . now running smoother
